icons_format = "{icon}"
[icons]
icons = "awesome4"

[icons.overrides]
bat = [" ", " ", " ", " ", " "]
bat_charging = " "

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#24273aAA"
idle_fg = "#cad3f5"

info_bg = "#24273aAA"
info_fg = "#8aadf4"

warning_bg = "#24273a"
warning_fg = "#eed49f"

critical_bg = "#24273a"
critical_fg = "#ed8796"

separator = " | "
separator_bg = "#24273aAA"
separator_fg = "#6e738d"

# ---------------------------
#   CPU
# ---------------------------
[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $barchart $frequency{ $boost|} "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

# ---------------------------
#   MEMORY
# ---------------------------
[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

# ---------------------------
#   TEMPERATURE (CPU Tctl)
# ---------------------------
[[block]]
block = "temperature"
format = " $icon $max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "k10temp-pci-*"

# ---------------------------
#   SOUND
# ---------------------------
[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# ---------------------------
#   BACKLIGHT
# ---------------------------
[[block]]
block = "backlight"
device = "amdgpu_bl1"

# ---------------------------
#   NETWORK
# ---------------------------
[[block]]
block = "net"
interval = 60
format = " $icon {$signal_strength} "

# ---------------------------
#   HUE SHIFT
# ---------------------------
[[block]]
block = "hueshift"
hue_shifter = "wlsunset"
step = 50
click_temp = 3500

# ---------------------------
#   MUSIC (MPRIS)
# ---------------------------
[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20)  $prev $play $next |}"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"

# ---------------------------
#   TIME
# ---------------------------
[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d/%m %H:%M') "

# ---------------------------
#   BATTERY
# ---------------------------
[[block]]
block = "battery"
format = " $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
device = "DisplayDevice"
driver = "upower"


# ---------------------------
#   APP MENU
# ---------------------------
[[block]]
block = "custom"
command  = "echo 󰍜"
[[block.click]]
button = "left"
cmd = "$HOME/.config/wofi/scripts/appmenu.sh"

# ---------------------------
#   POWER MENU
# ---------------------------
[[block]]
block = "menu"
text = "⏻ "
[[block.items]]
display = " → Sleep ← "
cmd = "systemctl suspend"
[[block.items]]
display = " → Power Off ← "
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " → Reboot ← "
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"

